### ISSUE TITLE
怎么安装呢

### ISSUE THREAD

**Issue by Feng-Hailing** [yichengchen/ATV-Bilibili-live-demo#1]
大佬，想在ATV上安装 Bilibili客户端，奈何官方没有App。
没想到这里有代码，应该怎么安装到设备上呢？ 求指引

<img width="1986" alt="image" src="https://user-images.githubusercontent.com/28183404/115120205-ce70ff00-9fde-11eb-8b4a-332a64f22b51.png">

另外，工程里似乎缺少标记的文件

**Comment by yichengchen** [comment]
执行pod install 后打开.xcworkspace文件。编译安装哈

**Comment by Feng-Hailing** [comment]
YES! 安装成功，谢谢 😊

**Comment by yichengchen** [comment]
基本上所有功能要先登录才会显示出来哈

**Comment by Thetigerwu** [comment]
请教大佬 有空时 能不能给个详细的安装教程 我完全不会呢 先谢谢大佬了

**Comment by Thetigerwu** [comment]
谢谢大佬

**Comment by insulaz** [comment]
菜鸡一整个爆哭。折腾了好几天，从opencore黑苹果开始搞，搞了个摇摇欲坠动不动就死机五国语言的版本，再跌跌撞撞搞好了Xcode和cocoa pods， 直到现在终于稀里糊涂在atv里看起来b站了。感谢大佬！
